### ISSUE TITLE
'hdropts' has incorrect type (expected dict, got list)

### ISSUE THREAD

**Issue by pgigis** [alexmarder/traceutils#1]
Hi, first of all, thank you for making the code publicly available.

When I parse the following Atlas traceroute

{
  "af": 4,
  "dst_addr": "104.16.63.210",
  "dst_name": "104.16.63.210",
  "endtime": 1496607139,
  "from": "130.125.97.233",
  "fw": 4770,
  "group_id": 8803752,
  "lts": 108,
  "msm_id": 8803752,
  "msm_name": "Traceroute",
  "paris_id": 1,
  "prb_id": 2973,
  "proto": "TCP",
  "result": [
    {
      "hop": 1,
      "result": [
        {
          "from": "130.125.97.3",
          "rtt": 266.144,
          "size": 28,
          "ttl": 255
        },
        {
          "from": "130.125.97.3",
          "rtt": 35.224,
          "size": 28,
          "ttl": 255
        },
        {
          "from": "130.125.97.3",
          "rtt": 14.186,
          "size": 28,
          "ttl": 255
        }
      ]
    },
    {
      "hop": 2,
      "result": [
        {
          "from": "192.42.42.18",
          "rtt": 26.83,
          "size": 28,
          "ttl": 254
        },
        {
          "from": "192.42.42.18",
          "rtt": 10.241,
          "size": 28,
          "ttl": 254
        },
        {
          "from": "192.42.42.18",
          "rtt": 14.034,
          "size": 28,
          "ttl": 254
        }
      ]
    },
    {
      "hop": 3,
      "result": [
        {
          "from": "192.42.42.33",
          "rtt": 14.913,
          "size": 68,
          "ttl": 253
        },
        {
          "from": "192.42.42.33",
          "rtt": 8.921,
          "size": 68,
          "ttl": 253
        },
        {
          "from": "192.42.42.33",
          "rtt": 3.174,
          "size": 68,
          "ttl": 253
        }
      ]
    },
    {
      "hop": 4,
      "result": [
        {
          "from": "130.59.37.166",
          "rtt": 39.292,
          "size": 28,
          "ttl": 252
        },
        {
          "from": "130.59.37.166",
          "rtt": 33.952,
          "size": 28,
          "ttl": 252
        },
        {
          "from": "130.59.37.166",
          "rtt": 66.116,
          "size": 28,
          "ttl": 252
        }
      ]
    },
    {
      "hop": 5,
      "result": [
        {
          "from": "130.59.36.70",
          "rtt": 34.905,
          "size": 68,
          "ttl": 251
        },
        {
          "from": "130.59.36.70",
          "rtt": 11.748,
          "size": 68,
          "ttl": 251
        },
        {
          "from": "130.59.36.70",
          "rtt": 35.136,
          "size": 68,
          "ttl": 251
        }
      ]
    },
    {
      "hop": 6,
      "result": [
        {
          "from": "130.59.38.193",
          "rtt": 32.035,
          "size": 68,
          "ttl": 250
        },
        {
          "from": "130.59.38.193",
          "rtt": 39.948,
          "size": 68,
          "ttl": 250
        },
        {
          "from": "130.59.38.193",
          "rtt": 41.864,
          "size": 68,
          "ttl": 250
        }
      ]
    },
    {
      "hop": 7,
      "result": [
        {
          "from": "130.59.38.82",
          "rtt": 13.114,
          "size": 28,
          "ttl": 249
        },
        {
          "from": "130.59.38.82",
          "rtt": 76.499,
          "size": 28,
          "ttl": 249
        },
        {
          "from": "130.59.38.82",
          "rtt": 35.71,
          "size": 28,
          "ttl": 249
        }
      ]
    },
    {
      "hop": 8,
      "result": [
        {
          "from": "80.249.211.140",
          "rtt": 28.333,
          "size": 28,
          "ttl": 248
        },
        {
          "from": "80.249.211.140",
          "rtt": 47.505,
          "size": 28,
          "ttl": 248
        },
        {
          "from": "80.249.211.140",
          "rtt": 51.679,
          "size": 28,
          "ttl": 248
        }
      ]
    },
    {
      "hop": 9,
      "result": [
        {
          "flags": "SA",
          "from": "104.16.63.210",
          "hdropts": [
            {
              "mss": 1460
            }
          ],
          "rtt": 39.155,
          "size": 4,
          "ttl": 56
        },
        {
          "flags": "SA",
          "from": "104.16.63.210",
          "hdropts": [
            {
              "mss": 1460
            }
          ],
          "rtt": 19.671,
          "size": 4,
          "ttl": 56
        },
        {
          "flags": "SA",
          "from": "104.16.63.210",
          "hdropts": [
            {
              "mss": 1460
            }
          ],
          "rtt": 19.608,
          "size": 4,
          "ttl": 56
        }
      ]
    }
  ],
  "size": 48,
  "src_addr": "130.125.97.233",
  "timestamp": 1496607136,
  "type": "traceroute"
}

I have the following error:
TypeError: Argument 'hdropts' has incorrect type (expected dict, got list) ?

It seems that hdropts is list instead of dict

**Comment by alexmarder** [comment]
I merged your fix. I assume that resolved the problem?

**Comment by pgigis** [comment]
Yes, thank you!
